services:
  npc:
    build:
      context: .
      dockerfile: Dockerfile
    image: npc:1.0.2
    container_name: npc
    restart: always
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      TZ: Asia/Shanghai
      CODE_SERVER_PASSWORD: "password"
